import type { WritingExercise } from "@/lib/writing";

// Câu 51 là bản scan không kèm đáp án. Các câu dưới đây là lời giải tham khảo
// biên soạn theo ngữ cảnh từng đề; không dùng để chấm khớp chữ tuyệt đối.
const question51: Array<[string, string, string, string, string, string[]]> = [
  [
    "Tuyển thành viên câu lạc bộ ảnh",
    "새 회원을 모집합니다",
    "시간이 없어서 걱정되십니까",
    "Câu mở đầu thông báo mục đích tuyển người; sau 이번에 cần một mệnh đề trần thuật trang trọng.",
    "Câu sau là 걱정하지 마세요 và lịch luyện tập buổi tối, nên câu hỏi phải nêu nỗi lo về thời gian.",
    ["polite", "if"],
  ],
  [
    "Tuyển phóng viên blog",
    "기자 분들을 모집합니다",
    "관심이 있으신 분이라면",
    "Đoạn đầu giới thiệu người sẽ kể chuyện địa phương bằng chữ, ảnh và video; chỗ trống kết bằng lời tuyển phóng viên.",
    "Ngay sau chỗ trống là 누구나 환영합니다, vì vậy dùng điều kiện ‘nếu quan tâm’ để mở rộng đối tượng.",
    ["polite", "if"],
  ],
  [
    "Câu lạc bộ aerobic",
    "회원들을 모집합니다",
    "처음이라서 걱정되십니까",
    "Thông báo nêu mục đích tăng sức khỏe cộng đồng, sau đó mới mời người quan tâm tham gia.",
    "Câu tiếp theo trấn an và hứa giáo viên hướng dẫn từ đầu; điều người đọc lo là chưa từng tập.",
    ["polite", "if"],
  ],
  [
    "Thông báo sửa trường",
    "조금 불편하시더라도 양해해 주시기 바랍니다",
    "안전하게 공사를 마치도록",
    "Sau thông tin có tiếng ồn, cần lời xin thông cảm lịch sự, không phải lời cấm.",
    "Câu cuối nói ‘최선을 다하겠습니다’; trước đó cần mục tiêu mà nhà trường sẽ cố gắng đạt được.",
    ["wish", "purpose"],
  ],
  [
    "Thông báo tạm nghỉ công ty du lịch",
    "문의해 주시기 바랍니다",
    "정상 영업을 하겠습니다",
    "예약센터 là kênh liên hệ khi có việc gấp; động từ 문의하다 kết hợp -아/어 주시기 바랍니다 tạo lời hướng dẫn.",
    "공사가 끝나는 즉시 đặt mốc thời gian; hành động phù hợp là hoạt động lại.",
    ["wish", "polite"],
  ],
  [
    "Tặng bàn học",
    "필요하신 분께 무료로 드리려고 합니다",
    "문자를 보내 주세요",
    "Vì có bàn không dùng, câu sau nên nói ý định tặng miễn phí để khớp tiêu đề.",
    "Người viết bận và không nhận điện thoại; yêu cầu nhắn tin thay vì gọi.",
    ["request", "purpose"],
  ],
  [
    "Tòa nhà cấm hút thuốc",
    "담배를 피우지 마십시오",
    "벌금을 내셔야 합니다",
    "금연 건물 kéo theo lệnh cấm hút thuốc trong toàn bộ tòa nhà.",
    "위반한 경우에는 là điều kiện vi phạm; hệ quả hợp lý là nộp phạt.",
    ["polite", "should"],
  ],
  [
    "Trả lời khách về đơn hàng chậm",
    "배송이 늦어질 수 있습니다",
    "조금만 더 기다려 주십시오",
    "Hàng từ nước ngoài về nên không thể hứa giao ngay; -ㄹ 수 있다 diễn tả khả năng chậm.",
    "Sau lời xin lỗi cần đề nghị khách chờ thêm trước câu mong thông cảm.",
    ["can", "request"],
  ],
  [
    "Mời cấp trên đến nhà",
    "잘하지 못합니다",
    "두 날 모두 괜찮습니다",
    "그렇지만 요리는 자신이 있습니다 đối lập với việc người viết chưa giỏi công việc.",
    "Người viết hỏi chọn thứ bảy hoặc chủ nhật; câu sau phải cho biết cả hai ngày đều phù hợp.",
    ["contrast", "polite"],
  ],
  [
    "Sửa trung tâm sinh viên",
    "학생회관 공사를 진행합니다",
    "조심해서 다니시기 바랍니다",
    "Phần tiếp theo nói rõ tiếng ồn do thi công, vì vậy câu mở cần thông báo việc sửa trung tâm.",
    "Đường tầng 1–2 có xe công trình nên yêu cầu đi lại cẩn thận vì an toàn.",
    ["polite", "wish"],
  ],
  [
    "Buổi chào đón tân sinh viên",
    "정보를 얻을 수 있을",
    "회비를 준비하지 말고",
    "Buổi gặp cung cấp thông tin hữu ích cho đời sống trường học; -ㄹ 수 있다 diễn tả lợi ích nhận được.",
    "Câu đối chiếu nói sinh viên cũ cần chuẩn bị 20.000 won, còn tân sinh viên đến không phải trả phí.",
    ["can", "notinstead"],
  ],
  [
    "Tuyển việc làm thêm",
    "걱정되십니까",
    "학생들도 지원할 수 있습니다",
    "Ngay sau câu hỏi, bài khẳng định công việc không yêu cầu kinh nghiệm/học vấn; câu hỏi phải nêu nỗi lo thiếu kinh nghiệm.",
    "주부들뿐만 아니라 mở cấu trúc ‘không chỉ… mà còn…’; sinh viên là nhóm được mời tiếp theo.",
    ["can", "polite"],
  ],
  [
    "Tìm bạn Việt Nam trao đổi ngôn ngữ",
    "언어 교환을 추천해서",
    "함께 언어를 연습하고 싶습니다",
    "Bạn bè đi du học trước giới thiệu cách trao đổi ngôn ngữ, dẫn tới ý định của người viết.",
    "Sau 만나서 cần hoạt động diễn ra khi gặp, phù hợp mục tiêu luyện ngôn ngữ.",
    ["purpose", "polite"],
  ],
  [
    "Lớp nấu món Hàn",
    "궁금하지 않으십니까",
    "직접 내셔야 합니다",
    "Câu hỏi gợi sự tò mò về món ăn do chính mình làm; 뒤의 물음표 đòi dạng nghi vấn.",
    "수업료는 무료이지만 đối lập với chi phí nguyên liệu học viên tự trả.",
    ["contrast", "should"],
  ],
  [
    "Đường dành riêng cho xe đạp",
    "금지되어 있습니다",
    "사고가 날 수 있습니다",
    "Đường chỉ cho xe đạp nên người đi bộ không được vào; -되어 있다 diễn tả quy định hiện hành.",
    "그렇지 않으면 nối với hướng dẫn đi trên vỉa hè, vì vậy nêu nguy cơ tai nạn.",
    ["can", "polite"],
  ],
  [
    "Thư gửi cha mẹ khi du học",
    "이제는 많이 익숙해졌습니다",
    "부모님이 보고 싶습니다",
    "Đoạn sau kể đã có bạn tốt, cho thấy sự cô đơn ban đầu đã giảm và người viết quen cuộc sống mới.",
    "하지만 tạo chuyển ý: dù quen cuộc sống Hàn Quốc, người viết vẫn nhớ quê và cha mẹ.",
    ["contrast", "polite"],
  ],
  [
    "Hướng dẫn chuyến đi Việt Nam",
    "불편함이 없으시기 바랍니다",
    "궁금한 점이 있으면 연락해 주십시오",
    "Lời nhắc chuẩn bị đồ nhằm giúp khách tránh bất tiện trong hành trình.",
    "Sau 그 밖에도 và trước số điện thoại là lời mời liên hệ khi còn thắc mắc.",
    ["wish", "if"],
  ],
  [
    "Thư chào đồng nghiệp mới",
    "이 회사에서 일하고 싶었는데 입사하게 되어서",
    "열심히 배우겠습니다",
    "Người viết kể mơ làm ở công ty từ nhỏ; nay được vào làm nên cảm thấy rất vui và vinh dự.",
    "Ngay sau câu hứa giúp các tiền bối là lời cam kết học hỏi trước khi xin chỉ bảo.",
    ["because", "polite"],
  ],
  [
    "Để lại lời nhắn cho đồng nghiệp",
    "일찍 도착하신다고 합니다",
    "읽으시면",
    "예정보다 tạo phép so sánh thời gian; giám đốc đến sớm nên người viết phải đi đón trước.",
    "확인 후 답장을 보내… là chuỗi hành động; điều kiện ‘khi đọc được’ nối tự nhiên.",
    ["if", "request"],
  ],
  [
    "Thiệp mời kết hôn",
    "이루게 되었습니다",
    "축복해 주십시오",
    "한 가정을 이루다 là kết hợp từ thường dùng khi nói hai người lập gia đình.",
    "Sau lời mời tham dự, lời đề nghị chúc phúc phù hợp ngữ cảnh thiệp cưới.",
    ["polite", "request"],
  ],
  [
    "Câu lạc bộ ảnh tuyển người",
    "누구나 가입할 수 있습니다",
    "함께 사진을 찍어 보시겠습니까",
    "Điều kiện duy nhất là quan tâm nhiếp ảnh; 누구나 가입할 수 있다 cho thấy câu lạc bộ mở.",
    "Câu sau yêu cầu đăng ký ngay, nên chỗ trống là lời mời tham gia dạng nghi vấn.",
    ["can", "polite"],
  ],
  [
    "Xin nghỉ học vì đau bụng",
    "가지 못할 것 같습니다",
    "학교에 가겠습니다",
    "Đau bụng dù uống thuốc nên ngày mai có lẽ không thể đến trường; giữ giọng lịch sự với giáo viên.",
    "Nếu sáng mai khỏe hơn thì người viết sẽ tới lớp, tạo đối ứng với khả năng nghỉ.",
    ["if", "polite"],
  ],
  [
    "Tìm bạn đồng hành",
    "여행하니까 외롭습니다",
    "함께 여행할 친구를 찾습니다",
    "Đoạn đầu kể đi một mình, sau đó bổ sung rào cản ngôn ngữ; cô đơn là khó khăn thứ nhất.",
    "그래서 đánh dấu kết luận: cần người cùng đi, lý tưởng là nói được tiếng Việt.",
    ["because", "polite"],
  ],
  [
    "Lời mời dự đám cưới",
    "함께 살아가려고 합니다",
    "큰 힘이 될 것입니다",
    "Từ nay hai người nhìn cùng một hướng; chỗ trống cần lời hứa sống bên nhau.",
    "여러분의 축복과 격려가 là chủ ngữ, kết quả là nguồn động viên cho đôi vợ chồng.",
    ["purpose", "polite"],
  ],
  [
    "Thiệp cưới trang trọng",
    "결혼식을 올리게 되었습니다",
    "앞날을 축복해 주시기 바랍니다",
    "Sau lời mời họ hàng và bạn bè, thông báo cử hành hôn lễ là nội dung trung tâm.",
    "Hai người bắt đầu cuộc sống mới nên kết bằng lời mong khách chúc phúc.",
    ["wish", "polite"],
  ],
  [
    "Thư cảm ơn sau tang lễ",
    "극복하고 있습니다",
    "하기를 바랍니다",
    "Lời chia buồn giúp gia đình vượt qua nỗi đau; -고 있다 cho biết quá trình đang tiếp diễn.",
    "가정에 건강과 행복이 늘 함께… là lời chúc, kết tự nhiên bằng -기를 바랍니다.",
    ["wish", "polite"],
  ],
  [
    "Kết quả phân công người hỗ trợ",
    "신청이 늦은 학생에게는 배정되지 않았습니다",
    "개별적으로 연락을 드리겠습니다",
    "Người mới được ưu tiên, các chỗ còn lại phân theo thứ tự đăng ký; vì vậy người đăng ký muộn có thể không được phân công.",
    "Người được phân công sẽ nhận thông tin liên hệ sau; câu tiếp theo yêu cầu gặp ít nhất mỗi tuần một lần.",
    ["polite", "request"],
  ],
  [
    "Ưu đãi tại hiệu sách",
    "외국인 유학생에게 할인 혜택을 드립니다",
    "학생증이 없으셔도 괜찮습니다",
    "Hai dòng tiếp theo liệt kê mức giảm cho sách tiếng Hàn và chuyên ngành, nên câu mở nói chương trình giảm giá.",
    "Câu sau nói có thể dùng giấy tờ tùy thân để nhận giảm giá, nên thiếu thẻ sinh viên vẫn được chấp nhận.",
    ["if", "can"],
  ],
  [
    "Mời thầy cô dự Tết",
    "설날 모임을 열기로 했습니다",
    "참석하실 수 있으십니까",
    "Đoạn sau nói đồ ăn các nước trong buổi gặp, nên chỗ đầu thông báo tổ chức sự kiện Tết.",
    "혹시 mở câu hỏi lịch sự về khả năng tham dự của thầy/cô.",
    ["polite", "can"],
  ],
  [
    "Tìm bạn tập thể dục",
    "함께 운동할 분을 찾습니다",
    "평일 오전에 운동하고 싶습니다",
    "Tập một mình nhiều lần thất bại nên người viết cần người đồng hành.",
    "Câu sau nói sau 7 giờ tối không thể, nên chọn khung buổi sáng ngày thường.",
    ["polite", "purpose"],
  ],
  [
    "Câu lạc bộ nói tiếng Hàn",
    "다른 언어로 말하는",
    "한국어 말하기 실력이 늘 수 있습니다",
    "Quy tắc là chỉ nói tiếng Hàn; trường hợp dùng ngôn ngữ khác phải nộp 1.000 won.",
    "이렇게 해야 đặt điều kiện để tiến bộ nói tiếng Hàn, khớp câu cuối.",
    ["if", "can"],
  ],
  [
    "Quy định phòng đọc",
    "열람실을 이용할 수 없습니다",
    "자리를 비워 주셔야 합니다",
    "Không lấy vé ghế thì không được dùng phòng; -ㄹ 수 없다 diễn tả điều kiện sử dụng.",
    "Nếu không gia hạn trước giờ rời phòng, phải nhường chỗ cho người đang chờ.",
    ["can", "should"],
  ],
  [
    "Xin thi bù giữa kỳ",
    "할아버지께서 편찮으셔서 시험을 보지 못했습니다",
    "다시 시험을 볼 수 있을까요",
    "Lý do vắng kỳ thi phải liên hệ việc ông bị bệnh đột ngột, phù hợp câu sau báo ông đã khá hơn.",
    "Người viết muốn dự thi; câu hỏi lịch sự xin cơ hội thi lại.",
    ["because", "can"],
  ],
  [
    "Thông báo bảo hiểm y tế",
    "보험 가입 증명서를 제출해야 합니다",
    "보험에 가입하지 않으면 보상을 받을 수 없습니다",
    "Câu sau nói không nộp giấy chứng nhận thì không thể đăng ký môn; chỗ trống là yêu cầu nộp giấy.",
    "Đoạn đối chiếu quyền lợi sau khi mua bảo hiểm với trường hợp chưa mua nên không được bồi thường.",
    ["should", "if"],
  ],
  [
    "Câu lạc bộ đọc văn học",
    "영문학을 전공한 선생님도 참여하십니다",
    "책을 미리 읽어 오셔야 합니다",
    "Câu kế nói giáo viên học văn học Anh ở Anh; chỗ trước giới thiệu sự tham gia của người ấy.",
    "Buổi gặp sẽ thảo luận sách đã báo trước trên blog, nên người tham dự cần đọc trước.",
    ["should", "polite"],
  ],
  [
    "Thiệp cưới và hướng dẫn đi lại",
    "저희 결혼을 축하해 주시기 바랍니다",
    "대중교통을 이용해 주십시오",
    "Lời mời đến dự cần hoàn thành trước khi thông báo vấn đề bãi xe.",
    "Vì chỗ đỗ xe hẹp, nên khuyên đi xe buýt hoặc tàu điện.",
    ["wish", "request"],
  ],
  [
    "Quảng cáo tập thể dục tại nhà",
    "운동할 시간이 없으십니까",
    "쉽게 운동할 수 있습니다",
    "Sau câu hỏi, sản phẩm mời dành 10 phút mỗi ngày; nêu nỗi lo thiếu thời gian.",
    "Vừa xem TV ở nhà vừa tập được, nhấn mạnh tính dễ và tiện thay vì tập ngoài trời.",
    ["can", "polite"],
  ],
  [
    "Nhờ bạn dẫn thăm quê",
    "출장을 갑니다",
    "전화번호를 다시 알려 줄 수 있습니까",
    "Lý do đến quê bạn là chuyến công tác của công ty tuần sau.",
    "Người viết đổi điện thoại nên mất danh bạ; cần xin lại số liên lạc để hẹn gặp.",
    ["request", "can"],
  ],
  [
    "Gửi lời nhắn lên radio",
    "사연을 보냅니다",
    "이렇게 말해 주십시오",
    "Trước đây chỉ nghe, lần này lần đầu gửi chuyện đến chương trình vì kỷ niệm 100 ngày.",
    "Sau chỗ trống là câu trích dẫn ‘사랑해’, nên cần lời dẫn nhờ người dẫn nói chính câu ấy với bạn gái.",
    ["request", "polite"],
  ],
  [
    "Xin gia hạn nộp bài",
    "제때 제출하지 못할 것 같습니다",
    "다음 주에 제출해도 괜찮겠습니까",
    "Vì việc gấp và phải về Trung Quốc, không thể nộp đúng giờ ngày mai.",
    "Sau lời xin lỗi cần câu hỏi lịch sự xin thời hạn khác; cách viết cụ thể có thể thay đổi.",
    ["can", "polite"],
  ],
  [
    "Thông báo thang máy hỏng",
    "엘리베이터를 이용할 수 없습니다",
    "계단을 이용해 주십시오",
    "Thang máy hỏng từ sáng nên hiện tại không thể dùng.",
    "Để di chuyển trong lúc chờ sửa, đề nghị dùng cầu thang.",
    ["can", "request"],
  ],
  [
    "Đổi lịch đặt phòng",
    "변경하고 싶습니다",
    "연락해 주시면 감사하겠습니다",
    "Vì lịch du lịch thay đổi, người đặt muốn đổi ngày lưu trú từ 2 đêm sang 3 đêm.",
    "Người viết đăng bài vì gấp, mong cơ sở lưu trú xác nhận và liên lạc sau khi kiểm tra.",
    ["request", "polite"],
  ],
  [
    "Đánh giá nơi lưu trú",
    "마음에 들었습니다",
    "여행하기 편리했습니다",
    "Người viết liệt kê cảnh, tiện nghi và bữa sáng đều tốt; câu tổng kết là hài lòng.",
    "Các điểm tham quan ở gần nên di chuyển thuận tiện, củng cố lời giới thiệu.",
    ["polite", "because"],
  ],
  [
    "Đổi cỡ giày",
    "작았습니다",
    "어떻게 해야 합니까",
    "Sau khi tặng, bạn thử thấy giày nhỏ nên cần đổi cỡ lớn hơn.",
    "Câu sau yêu cầu hướng dẫn cách đổi; chỗ hỏi cần hỏi thủ tục hoặc việc phải làm.",
    ["polite", "should"],
  ],
  [
    "Lời cảm ơn đồng nghiệp",
    "부족한 점도 있었을 것입니다",
    "다시 만나기를 바랍니다",
    "Người viết nói đã cố gắng nhưng vẫn có thể thiếu sót, rồi xin đồng nghiệp thông cảm.",
    "Trước khi về nước, lời chúc gặp lại phù hợp câu ‘기회가 되어’.",
    ["wish", "polite"],
  ],
  [
    "Chúc mừng thăng chức",
    "진심으로 축하드립니다",
    "좋은 일만 있기를 바랍니다",
    "Sau khi biết người nhận được thăng chức, câu mở thư cần chúc mừng trang trọng.",
    "Thư kết bằng lời chúc tương lai tốt đẹp sau khi kỳ vọng đóng góp của người nhận.",
    ["wish", "polite"],
  ],
  [
    "Thư xin lỗi khách hàng",
    "받았습니다",
    "하지 않겠습니다",
    "질책을 받다 là kết hợp tự nhiên: người viết bị khách khiển trách do lời nói bất cẩn.",
    "다시는 이런 실수를… là lời cam kết không lặp lại lỗi.",
    ["polite", "notinstead"],
  ],
  [
    "Xin tài liệu ôn thi",
    "관련 자료를 어디에서 찾을 수 있습니까",
    "알려 주시면 감사하겠습니다",
    "Người viết không tìm được tài liệu cần cho kỳ thi; câu hỏi phải hỏi nơi tra cứu.",
    "Nếu hội biết tài liệu, người viết mong được chỉ dẫn; dùng điều kiện lịch sự.",
    ["can", "if"],
  ],
  [
    "Hỏi chi phí du học Đức",
    "유학을 가고 싶었습니다",
    "얼마나 듭니까",
    "Ước mơ nghề nghiệp thúc đẩy ý định ra nước ngoài học; nguồn có một tên nghề bị nhòe nên không suy đoán nghề cụ thể.",
    "Danh sách sinh hoạt, đi lại, ăn uống và sách là các khoản chi, cần hỏi tổng chi phí để chuẩn bị.",
    ["polite", "can"],
  ],
  [
    "Tư vấn khớp hông",
    "소리가 납니다",
    "병원에 가 봐야 할까요",
    "Bài mô tả tiếng phát ra khi đi bộ ở khớp hông trái, câu sau bổ sung cảm giác vướng.",
    "Dù chưa đau, người viết muốn bác sĩ tư vấn có cần đến khám hay không.",
    ["should", "polite"],
  ],
];

export const writing51: WritingExercise[] = question51.map((row, index) => ({
  id: `51-${index + 1}`,
  kind: 51,
  number: index + 1,
  title: row[0],
  image: `/writing/51-${String(index + 1).padStart(2, "0")}.webp`,
  source: "huongiu 50 câu 51 TOPIK II 쓰기.pdf",
  page: Math.ceil((index + 1) / 2),
  answers: { ㄱ: row[1], ㄴ: row[2] },
  explanations: { ㄱ: row[3], ㄴ: row[4] },
  grammar: row[5],
  ...([30, 48].includes(index)
    ? {
        reviewNote:
          "Một số chữ hoặc dấu câu trong bản scan không rõ/không khớp. Hãy đối chiếu ảnh đề gốc; lời giải chỉ là phương án theo ý định của đoạn văn.",
      }
    : {}),
}));
