import type { Lesson, Vocabulary } from "./models";
import { importedVocabulary, topikLessons } from "./source-catalog";

export const starterLessons: Lesson[] = [
  {
    id: "greetings",
    title: "Lời chào đầu tiên",
    korean: "안녕하세요",
    description:
      "Bắt đầu một cuộc trò chuyện bằng những lời chào thật tự nhiên.",
    level: 1,
    category: "Giao tiếp",
    motif: "sun",
    color: "peach",
    grammar: {
      pattern: "N + 입니다",
      explanation:
        "Dùng để giới thiệu hoặc khẳng định một cách trang trọng: “là…”.",
      example: "저는 학생입니다.",
      translation: "Tôi là học sinh.",
    },
  },
  {
    id: "daily",
    title: "Một ngày của mình",
    korean: "나의 하루",
    description: "Những từ quen thuộc từ khi thức dậy đến lúc về nhà.",
    level: 1,
    category: "Đời sống",
    motif: "home",
    color: "sage",
    grammar: {
      pattern: "V + 아요 / 어요",
      explanation:
        "Đuôi câu lịch sự thân mật, thường dùng trong hội thoại hằng ngày.",
      example: "저는 학교에 가요.",
      translation: "Tôi đi đến trường.",
    },
  },
  {
    id: "food",
    title: "Một chút vị Hàn",
    korean: "맛있는 한국",
    description: "Gọi món yêu thích và khám phá bàn ăn của người Hàn.",
    level: 1,
    category: "Ẩm thực",
    motif: "tea",
    color: "butter",
    grammar: {
      pattern: "N + 주세요",
      explanation: "Dùng khi muốn xin hoặc gọi một thứ gì đó một cách lịch sự.",
      example: "물 주세요.",
      translation: "Cho tôi nước với ạ.",
    },
  },
  {
    id: "travel",
    title: "Dạo quanh Seoul",
    korean: "서울 산책",
    description: "Hỏi đường, bắt tàu và khám phá một thành phố mới.",
    level: 2,
    category: "Du lịch",
    motif: "mountain",
    color: "blue",
    grammar: {
      pattern: "N + 에 가다",
      explanation: "Tiểu từ 에 chỉ đích đến, kết hợp với 가다 (đi).",
      example: "지하철역에 가요.",
      translation: "Tôi đi đến ga tàu điện ngầm.",
    },
  },
  {
    id: "feelings",
    title: "Nói điều mình nghĩ",
    korean: "마음의 이야기",
    description: "Diễn tả cảm xúc và những khoảnh khắc đáng nhớ.",
    level: 2,
    category: "Cảm xúc",
    motif: "flower",
    color: "rose",
    grammar: {
      pattern: "V + 고 싶다",
      explanation:
        "Kết hợp với động từ để diễn tả mong muốn làm một việc gì đó.",
      example: "한국에 가고 싶어요.",
      translation: "Tôi muốn đến Hàn Quốc.",
    },
  },
  {
    id: "study",
    title: "Học cùng nhau",
    korean: "함께 공부해요",
    description: "Từ vựng trường lớp để tự tin học cùng bạn bè.",
    level: 3,
    category: "Học tập",
    motif: "book",
    color: "lavender",
    grammar: {
      pattern: "V + 기 위해서",
      explanation: "Diễn tả mục đích: “để làm…”.",
      example: "한국어를 배우기 위해서 매일 공부해요.",
      translation: "Tôi học mỗi ngày để học tiếng Hàn.",
    },
  },
];

type SeedRow = [string, string, string, string, string, string?];
const rows: Record<string, SeedRow[]> = {
  greetings: [
    [
      "안녕하세요",
      "Xin chào",
      "annyeonghaseyo",
      "안녕하세요, 만나서 반갑습니다.",
      "Xin chào, rất vui được gặp bạn.",
      "Lời chào",
    ],
    [
      "감사합니다",
      "Cảm ơn",
      "gamsahamnida",
      "도와주셔서 감사합니다.",
      "Cảm ơn bạn đã giúp đỡ.",
      "Biểu đạt",
    ],
    [
      "친구",
      "Bạn bè",
      "chingu",
      "제 친구는 베트남 사람이에요.",
      "Bạn của tôi là người Việt Nam.",
    ],
    ["이름", "Tên", "ireum", "이름이 뭐예요?", "Bạn tên là gì?"],
    [
      "사람",
      "Người",
      "saram",
      "저는 베트남 사람이에요.",
      "Tôi là người Việt Nam.",
    ],
    [
      "만나다",
      "Gặp gỡ",
      "mannada",
      "내일 친구를 만나요.",
      "Ngày mai tôi gặp bạn.",
      "Động từ",
    ],
  ],
  daily: [
    ["학교", "Trường học", "hakgyo", "학교에 가요.", "Tôi đi đến trường."],
    ["집", "Nhà", "jip", "집에서 쉬어요.", "Tôi nghỉ ngơi ở nhà."],
    [
      "아침",
      "Buổi sáng",
      "achim",
      "아침에 운동해요.",
      "Tôi tập thể dục vào buổi sáng.",
    ],
    ["시간", "Thời gian", "sigan", "시간이 있어요?", "Bạn có thời gian không?"],
    [
      "일하다",
      "Làm việc",
      "ilhada",
      "저는 회사에서 일해요.",
      "Tôi làm việc ở công ty.",
      "Động từ",
    ],
    [
      "쉬다",
      "Nghỉ ngơi",
      "swida",
      "주말에 쉬어요.",
      "Tôi nghỉ ngơi vào cuối tuần.",
      "Động từ",
    ],
  ],
  food: [
    ["물", "Nước", "mul", "물 한 잔 주세요.", "Cho tôi một cốc nước với ạ."],
    ["밥", "Cơm", "bap", "같이 밥을 먹어요.", "Chúng ta cùng ăn cơm nhé."],
    ["차", "Trà", "cha", "따뜻한 차를 마셔요.", "Tôi uống trà ấm."],
    ["김치", "Kim chi", "gimchi", "김치가 맛있어요.", "Kim chi ngon."],
    ["먹다", "Ăn", "meokda", "아침을 먹어요.", "Tôi ăn sáng.", "Động từ"],
    [
      "맛있다",
      "Ngon",
      "masitda",
      "이 음식은 정말 맛있어요.",
      "Món ăn này thật sự ngon.",
      "Tính từ",
    ],
  ],
  travel: [
    [
      "여행",
      "Du lịch",
      "yeohaeng",
      "한국 여행을 준비해요.",
      "Tôi chuẩn bị cho chuyến du lịch Hàn Quốc.",
    ],
    [
      "지하철",
      "Tàu điện ngầm",
      "jihacheol",
      "지하철을 타요.",
      "Tôi đi tàu điện ngầm.",
    ],
    [
      "거리",
      "Con phố",
      "geori",
      "이 거리는 조용해요.",
      "Con phố này yên tĩnh.",
    ],
    ["지도", "Bản đồ", "jido", "지도를 봐요.", "Tôi xem bản đồ."],
    [
      "공원",
      "Công viên",
      "gongwon",
      "공원에서 산책해요.",
      "Tôi đi dạo trong công viên.",
    ],
    [
      "도착하다",
      "Đến nơi",
      "dochakhada",
      "서울에 도착했어요.",
      "Tôi đã đến Seoul.",
      "Động từ",
    ],
  ],
  feelings: [
    [
      "행복하다",
      "Hạnh phúc",
      "haengbokhada",
      "오늘은 행복해요.",
      "Hôm nay tôi hạnh phúc.",
      "Tính từ",
    ],
    [
      "기쁘다",
      "Vui mừng",
      "gippeuda",
      "친구를 만나서 기뻐요.",
      "Tôi vui vì gặp bạn.",
      "Tính từ",
    ],
    ["기억", "Ký ức", "gieok", "좋은 기억이 있어요.", "Tôi có một ký ức đẹp."],
    ["마음", "Tấm lòng", "maeum", "마음이 따뜻해요.", "Tấm lòng thật ấm áp."],
    [
      "걱정",
      "Sự lo lắng",
      "geokjeong",
      "걱정하지 마세요.",
      "Đừng lo lắng nhé.",
    ],
    [
      "꿈",
      "Ước mơ",
      "kkum",
      "제 꿈은 선생님이 되는 거예요.",
      "Ước mơ của tôi là trở thành giáo viên.",
    ],
  ],
  study: [
    [
      "경험",
      "Kinh nghiệm",
      "gyeongheom",
      "좋은 경험이 되었어요.",
      "Đó đã trở thành một trải nghiệm tốt.",
    ],
    [
      "목표",
      "Mục tiêu",
      "mokpyo",
      "올해 목표를 세웠어요.",
      "Tôi đã đặt mục tiêu cho năm nay.",
    ],
    [
      "노력",
      "Sự nỗ lực",
      "noryeok",
      "노력이 중요해요.",
      "Sự nỗ lực rất quan trọng.",
    ],
    [
      "이해하다",
      "Hiểu",
      "ihaehada",
      "이 문장을 이해했어요.",
      "Tôi đã hiểu câu này.",
      "Động từ",
    ],
    [
      "설명하다",
      "Giải thích",
      "seolmyeonghada",
      "선생님이 문법을 설명해요.",
      "Giáo viên giải thích ngữ pháp.",
      "Động từ",
    ],
    [
      "복습하다",
      "Ôn tập",
      "bokseuphada",
      "매일 단어를 복습해요.",
      "Tôi ôn từ vựng mỗi ngày.",
      "Động từ",
    ],
  ],
};
export const lessons: Lesson[] = [...starterLessons, ...topikLessons];
export const seedVocabulary: Vocabulary[] = [
  ...starterLessons.flatMap((lesson): Vocabulary[] =>
    rows[lesson.id].map((row, index) => ({
      id: `${lesson.id}-${index + 1}`,
      lessonId: lesson.id,
      korean: row[0],
      meaning: row[1],
      romanization: row[2],
      example: row[3],
      translation: row[4],
      wordType: row[5] ?? "Danh từ",
      level: lesson.level,
      status: "published",
      sourcePage: null,
    })),
  ),
  ...importedVocabulary,
];
